### ISSUE TITLE
Blacklisting items in categories.yml

### ISSUE THREAD

**Issue by H0tKinsS** [GroupeZ-dev/Plugins-Report#11]
### Terms

- [x] I'm using the very latest version of the plugin
- [x] I already searched on this [Github page](https://github.com/GroupeZ-dev/Plugins-Report/issues) to check if the same suggestion was already reported.
- [x] I already searched on the plugin wiki to know if a solution is already known.
- [x] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this or if the feature was already suggested.

### Plugin

zAuctionHouse

### Discord Username (optional)

h0tkinss

### Describe your suggestions

Add a posibility to blacklist certain items from appearing in a category.
f.e:
```
  tools:
    name: Tools
    materials:
    - material: GOLDEN_PICKAXE
    blacklist:
    - name: "Special pickaxe"
```
